### ISSUE TITLE
Uncaught ReferenceError: $ is not defined     at ui.js:1:1

### ISSUE THREAD

**Issue by agentydragon** [leonid-shevtsov/monkeysort#2]
hi :)

seems like at some point in the last 10 years it broke: 
![Screen Shot 2022-08-31 at 2 18 32 PM](https://user-images.githubusercontent.com/714892/187786455-1a1bbb54-a93f-41d7-8a0f-125910375a93.png)

**Comment by agentydragon** [comment]
already reported in: https://github.com/leonid-shevtsov/monkeysort/pull/1

**Comment by leonid-shevtsov** [comment]
Aaaand it's fixed 🎉
